apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '2'
  name: build-push-internal-registry-rollout-pr
  namespace: php-hello-dev
spec:
  pipelineRef:
    name: build-push-internal-registry-rollout
  taskRunTemplate:
    serviceAccountName: pipeline
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: shared-workspace
