apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- build-push-internal-registry-rollout.yaml
# - build-push-internal-registry-rollout-pr.yaml
- push-image-quay.yaml
- trigger-template.yaml
# # - trigger-binding.yaml
- event-listener.yaml
- webhook-route.yaml 
- shared-workspace-pvc.yaml
