apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- shared-workspace-pvc.yaml
- build-push-internal-registry.yaml
- trigger-template.yaml
- trigger-binding.yaml
- event-listener.yaml
- webhook-route.yaml 
