apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '2'
  name: push-image-quay
  namespace: php-hello-dev
spec:
  params:
    - name: SOURCE_IMAGE
      type: string
      description: Image to scan and push to Quay
      default: 'docker://image-registry.openshift-image-registry.svc:5000/php-hello-dev/php-hello:latest'
    - name: image-tag
      type: string
      description: Tag for pushed image
      default: latest
    - name: TLSVERIFY
      type: string
      description: Enable or Disable TLS verification
      default: 'false'
  tasks:
    - name: scan-image
      params:
        - name: image
          value: $(params.SOURCE_IMAGE)
        - name: insecure-skip-tls-verify
          value: $(params.TLSVERIFY)
      taskRef:
        kind: Task
        name: acs-image-check
    - name: skopeo-copy
      params:
        - name: srcImageURL
          value: $(params.SOURCE_IMAGE)
        - name: destImageURL
          value: 'docker://quay.io/chpeters/php-hello:$(params.IMAGE_TAG)'
        - name: srcTLSverify
          value: 'true'
        - name: destTLSverify
          value: 'true'
      runAfter:
        - scan-image
      taskRef:
        kind: ClusterTask
        name: skopeo-copy
      workspaces:
        - name: images-url
          workspace: shared-workspace
  workspaces:
    - name: shared-workspace
