apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '2'
  name: push-image-quay
  namespace: php-hello-dev
spec:
  params:
    - default: latest
      name: IMAGE_TAG
      type: string
  tasks:
    - name: skopeo-copy
      params:
        - name: srcImageURL
          value: 'docker://image-registry.openshift-image-registry.svc:5000/php-hello-dev/php-hello:latest'
        - name: destImageURL
          value: 'docker://quay.io/chpeters/php-hello:$(params.IMAGE_TAG)'
        - name: srcTLSverify
          value: 'true'
        - name: destTLSverify
          value: 'true'
      taskRef:
        kind: ClusterTask
        name: skopeo-copy
      workspaces:
        - name: images-url
          workspace: shared-workspace
  workspaces:
    - name: shared-workspace
      optional: false
