apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '2'
  name: push-image-quay
  namespace: php-hello-dev
spec:
  params:
    - name: SOURCE_IMAGE
      type: string
      description: Image to scan and push to Quay
      default: 'docker://image-registry.openshift-image-registry.svc:5000/php-hello-dev/php-hello:latest'
    - name: IMAGE_TAG
      type: string
      description: Tag for pushed image
      default: latest
    - name: ACS_SCAN_OUTPUT_FORMAT
      description: Ouput format for ACS scan results (json, cvs, pretty)
      type: string
      default: 'json'
    - name: TLSVERIFY
      type: string
      description: Enable or Disable TLS verification
      default: 'true'
  tasks:
    - name: acs-image-scan
      params:
        - name: image
          value: $(params.SOURCE_IMAGE)
        - name: rox_central_endpoint
          value: roxsecrets
        - name: rox_api_token
          value: roxsecrets
        - name: output_format
          value: $(params.ACS_SCAN_OUTPUT_FORMAT)
        - name: insecure-skip-tls-verify
          value: $(params.TLSVERIFY)
      taskRef:
        kind: Task
        name: acs-image-scan
      workspaces:
        - name: acs-image-scan
          workspace: quay-shared-workspace
    - name: skopeo-copy
      params:
        - name: srcImageURL
          value: $(params.SOURCE_IMAGE)
        - name: destImageURL
          value: 'docker://quay.io/chpeters/php-hello:$(params.IMAGE_TAG)'
        - name: srcTLSverify
          value: 'true'
        - name: destTLSverify
          value: 'true'
      runAfter:
        - acs-image-scan
      taskRef:
        kind: ClusterTask
        name: skopeo-copy
      workspaces:
        - name: images-url
          workspace: quay-shared-workspace
  workspaces:
    - name: quay-shared-workspace
