apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '3'
  name: build-push-internal-registry-pipeline-binding
  namespace: php-hello-dev
spec:
  params:
    - name: git-revision
      value: $(body.head_commit.id)
    - name: git-repo-url
      value: $(body.repository.url)
