---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '3'
  name: trigger-template-build-push-internal-registry-rollout
  namespace: php-hello-dev
spec:
  params:
    - name: git-revision
    - name: git-commit-message
    - name: git-repo-url
    - name: git-repo-name
    - name: content-type
    - name: pusher-name
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        annotations:
          argocd.argoproj.io/sync-wave: '2'
        generateName: build-push-internal-registry-rollout-
        labels:
          tekton.dev/pipeline: build-push-internal-registry-rollout
        namespace: php-hello-dev
      spec:
        params: []
        pipelineRef:
          name: build-push-internal-registry-rollout
        status: null
        workspaces:
          - name: shared-workspace
            persistentVolumeClaim:
              claimName: shared-workspace
