apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: build-push-internal-registry-trigger-template
  namespace: php-hello-dev
spec:
  params:
    - name: git-revision
    - name: git-repo-url
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        annotations:
          pipeline.openshift.io/started-by: admin
        generateName: build-push-internal-registry-
        labels:
          tekton.dev/pipeline: build-push-internal-registry
        namespace: php-hello-dev
      spec:
        params:
          - name: GIT_URL
            value: $(tt.params.git-repo-url)
          - name: GIT_BRANCH
            value: $(tt.params.git-revision)
          - name: OUTPUT_IMAGE
            value: demo-quay-app.registry.svc.cluster.local/admin/meat-helper
          - name: OUTPUT_TAG
            value: demo
        pipelineRef:
          name: build-push-internal-registry
        resources: []
        status: null
        workspaces:
          - name: php-hello-workspace
            persistentVolumeClaim:
              claimName: shared-workspace
