---
kind: Service
apiVersion: v1
metadata:
  name: el-event-listener-build-push-internal-registry-rollout
  namespace: php-hello-dev
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: event-listener-build-push-internal-registry-rollout
spec:
  ports:
    - name: http-listener
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: http-metrics
      protocol: TCP
      port: 9000
  selector:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: event-listener-build-push-internal-registry-rollout
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: el-build-push-internal-registry-rollout
  namespace: php-hello-dev
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: event-listener-build-push-internal-registry-rollout
spec:
  to:
    kind: Service
    name: el-event-listener-build-push-internal-registry-rollout
    weight: 100
  port:
    targetPort: http-listener
  wildcardPolicy: None
