kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: build-push-internal-registry-event-listener
  namespace: php-hello-dev
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: build-push-internal-registry-event-listener
spec:
  to:
    kind: Service
    name: el-build-push-internal-registry-event-listener
    weight: 100
  port:
    targetPort: 8080
  wildcardPolicy: None
