apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
  - path: replicas.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: php-hello
  - path: version.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: php-hello
