# Source: gitlab-operator/templates/openshift/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitlab-system:openshift:scc:nginx-ingress-scc
rules:
  - apiGroups:
      - security.openshift.io
    resourceNames:
      - gitlab-nginx-ingress-scc
    resources:
      - securitycontextconstraints
    verbs:
      - use
---
# Source: gitlab-operator/templates/openshift/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitlab-system:openshift:scc:nginx-ingress-scc
  namespace: gitlab-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gitlab-system:openshift:scc:nginx-ingress-scc
subjects:
  - kind: ServiceAccount
    name: gitlab-nginx-ingress
    namespace: gitlab-system
---
# Source: gitlab-operator/templates/openshift/scc.yaml
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
allowPrivilegedContainer: false
allowedCapabilities: null
apiVersion: security.openshift.io/v1
defaultAddCapabilities:
  - NET_BIND_SERVICE
fsGroup:
  type: MustRunAs
groups: []
kind: SecurityContextConstraints
metadata:
  name: gitlab-nginx-ingress-scc
priority: null
readOnlyRootFilesystem: false
requiredDropCapabilities:
  - ALL
runAsUser:
  type: MustRunAs
  uid: 101
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: MustRunAs
volumes:
  - secret
