kind: Service
apiVersion: v1
metadata:
  name: php-hello-dockerfile
  namespace: php-hello
  labels:
    app: php-hello-dockerfile
    app.kubernetes.io/component: php-hello-dockerfile
    app.kubernetes.io/instance: php-hello-dockerfile
    app.kubernetes.io/name: php-hello-dockerfile
    app.kubernetes.io/part-of: php-hello-dockerfile-app
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: php-hello-dockerfile
    deployment: php-hello-dockerfile

