# ---
# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization
#
# commonAnnotations:
#   argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
#
# resources:
#   - patch-argocd.yaml
#   - namespace.yaml
#   - operator-group.yaml
#   - subscription.yaml
#   - ./instance/overlays/internal-registry-integration
#
# patches:
#   - path: patch-resources.yaml
#     target:
#       group: platform.stackrox.io
#       kind: Central
#       name: central
#       version: v1alpha1
